name: ch-otp-task
version: '0.1.0.0'
category: research
author: Adam Szlachta
maintainer: adam.szlachta@gmail.com
copyright: Apache 2.0
license: BSD3
github: dktn/ch-otp-task
extra-source-files:
- README.md
dependencies:
- protolude
- monad-loops
- optparse-applicative
- random
- time
- psqueues
- hashable
- unordered-containers
- binary
- binary-orphans
- distributed-process
- distributed-process-simplelocalnet
default-extensions:
- NoImplicitPrelude
- OverloadedStrings
- DeriveGeneric
- DeriveAnyClass
executables:
  ch-otp-task:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O1 # O2
    dependencies:
    - base
